name: Test1
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04119660332798958
title: The Best Place for LLamas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5484845843166113
  lightness: 0.9984052402433008
  saturation: 0.8476024332921952
  rhythmicContrast: 0.21754708513617516
purpose: []
