name: Test1
favicon: null
layout_spectrum: 0.16803
typography_spectrum: 0.3056
title: The Best Place for Llamas
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#212121'
    - '#ded1c1'
    - '#982815'
    - '#a69e93'
    - '#a84f40'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
